services:
  - type: web
    name: medtech-backend
    env: python
    rootDir: healthconnect-backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    autoDeploy: true
