const { sendEmail } = require('./mailer');

function formatDate(value) {
  const d = new Date(value || Date.now());
  if (Number.isNaN(d.getTime())) {
    return new Date().toLocaleDateString('en-IN');
  }
  return d.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
}

async function sendPrescriptionEmail(patientEmail, prescriptionData = {}, pdfBuffer = null) {
  const recipient = String(patientEmail || '').trim();
  if (!recipient) {
    return { success: false, error: 'Patient email is missing' };
  }

  const patientName = String(prescriptionData.patientName || 'Patient').trim();
  const doctorName = String(prescriptionData.doctorName || 'Doctor').trim();
  const dateText = formatDate(prescriptionData.date);
  const prescriptionId = String(prescriptionData.prescriptionId || '').trim();

  const subject = 'Your Prescription - MedTech Clinic';
  const textContent = [
    `Hello ${patientName},`,
    '',
    'Your prescription has been generated by your doctor.',
    '',
    `Doctor: ${doctorName}`,
    `Date: ${dateText}`,
    '',
    'Please find your prescription attached.',
    '',
    'Regards,',
    'MedTech Clinic',
  ].join('\n');

  const htmlContent = `
    <div style="font-family:Arial,Helvetica,sans-serif;max-width:560px;margin:0 auto;border:1px solid #e5e7eb;border-radius:12px;overflow:hidden">
      <div style="background:#0f766e;padding:18px 22px;color:white;font-size:20px;font-weight:700">MedTech Clinic</div>
      <div style="padding:24px;background:#ffffff;color:#111827;line-height:1.5">
        <p>Hello ${patientName},</p>
        <p>Your prescription has been generated by your doctor.</p>
        <p><strong>Doctor:</strong> ${doctorName}<br /><strong>Date:</strong> ${dateText}</p>
        <p>Please find your prescription attached.</p>
        <p style="margin-top:16px">Regards,<br />MedTech Clinic</p>
      </div>
    </div>
  `;

  const attachments = [];
  if (pdfBuffer) {
    attachments.push({
      filename: `prescription_${prescriptionId || Date.now()}.pdf`,
      content: pdfBuffer,
      contentType: 'application/pdf',
    });
  }

  return sendEmail({
    toEmail: recipient,
    subject,
    htmlContent,
    textContent,
    retries: 1,
    attachments,
  });
}

module.exports = {
  sendPrescriptionEmail,
};
